// Generated by gencpp from file lab1/ComplexNumber.msg
// DO NOT EDIT!


#ifndef LAB1_MESSAGE_COMPLEXNUMBER_H
#define LAB1_MESSAGE_COMPLEXNUMBER_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lab1
{
template <class ContainerAllocator>
struct ComplexNumber_
{
  typedef ComplexNumber_<ContainerAllocator> Type;

  ComplexNumber_()
    : real(0.0)
    , imaginary(0.0)  {
    }
  ComplexNumber_(const ContainerAllocator& _alloc)
    : real(0.0)
    , imaginary(0.0)  {
  (void)_alloc;
    }



   typedef float _real_type;
  _real_type real;

   typedef float _imaginary_type;
  _imaginary_type imaginary;





  typedef boost::shared_ptr< ::lab1::ComplexNumber_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lab1::ComplexNumber_<ContainerAllocator> const> ConstPtr;

}; // struct ComplexNumber_

typedef ::lab1::ComplexNumber_<std::allocator<void> > ComplexNumber;

typedef boost::shared_ptr< ::lab1::ComplexNumber > ComplexNumberPtr;
typedef boost::shared_ptr< ::lab1::ComplexNumber const> ComplexNumberConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lab1::ComplexNumber_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lab1::ComplexNumber_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::lab1::ComplexNumber_<ContainerAllocator1> & lhs, const ::lab1::ComplexNumber_<ContainerAllocator2> & rhs)
{
  return lhs.real == rhs.real &&
    lhs.imaginary == rhs.imaginary;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::lab1::ComplexNumber_<ContainerAllocator1> & lhs, const ::lab1::ComplexNumber_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace lab1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::lab1::ComplexNumber_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lab1::ComplexNumber_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lab1::ComplexNumber_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lab1::ComplexNumber_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lab1::ComplexNumber_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lab1::ComplexNumber_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lab1::ComplexNumber_<ContainerAllocator> >
{
  static const char* value()
  {
    return "54da470dccf15d60bd273ab751e1c0a1";
  }

  static const char* value(const ::lab1::ComplexNumber_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x54da470dccf15d60ULL;
  static const uint64_t static_value2 = 0xbd273ab751e1c0a1ULL;
};

template<class ContainerAllocator>
struct DataType< ::lab1::ComplexNumber_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lab1/ComplexNumber";
  }

  static const char* value(const ::lab1::ComplexNumber_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lab1::ComplexNumber_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 real\n"
"float32 imaginary\n"
;
  }

  static const char* value(const ::lab1::ComplexNumber_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lab1::ComplexNumber_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.real);
      stream.next(m.imaginary);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ComplexNumber_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lab1::ComplexNumber_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lab1::ComplexNumber_<ContainerAllocator>& v)
  {
    s << indent << "real: ";
    Printer<float>::stream(s, indent + "  ", v.real);
    s << indent << "imaginary: ";
    Printer<float>::stream(s, indent + "  ", v.imaginary);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LAB1_MESSAGE_COMPLEXNUMBER_H
